routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::get('password/reset/{token}','Auth\ResetPasswordController@showResetForm')->name('register.reset');
Route::get('password/reset/','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email','Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('register','Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register','Auth\RegisterController@register');
Route::post('login','Auth\LoginController@login');
Route::get('login','Auth\LoginController@showLoginForm')->name('login');


Route::group(['middleware' => ['auth']], function () {
    Route::post('logout','Auth\LoginController@logout')->name('logout');
    Route::resource('koperasi','KoperasiController')->except(['destroy']);;
    Route::delete('koperasi/delete','KoperasiController@destroy')->name('koperasi.destroy');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('jenis_koperasi','JenisKoperasiController')->except(['destroy']);
    Route::delete('jenis_koperasi/delete','JenisKoperasiController@destroy')->name('jenisKoperasi.destroy');
    Route::get('role','ManagementUserController@formRole')->name('role');
    Route::post('role','ManagementUserController@addRole');
    Route::get('user','ManagementUserController@allUsers')->name('user');
    Route::get('user/create','ManagementUserController@createUser')->name('user.create');
    Route::post('user','ManagementUserController@storeUser')->name('user.store');
    Route::delete('user','ManagementUserController@destroyUser')->name('user.destroy');
    Route::get('user/{id}/edit','ManagementUserController@editUser')->name('user.edit');
    Route::put('user/{id}','ManagementUserController@updateUser')->name('user.update');
    Route::get('file/create','FileController@createFileKoperasi')->name('file.create');
    Route::post('file','FileController@storeFile')->name('file.store');
    Route::get('file/{id}','FileController@showFileKoperasi')->name('fileKoperasi.show');
    Route::delete('file/delete','FileController@destroyFileKoperasi')->name('fileKoperasi.destroy');
    Route::get('file/{id}/edit','FileController@editFileKoperasi');
    Route::put('file/{id}','FileController@updateFileKoperasi');
    Route::get('allKoperasi','KoperasiController@allKoperasi')->name('all.koperasi');
    Route::get('detKoperasi/{id}','KoperasiController@detKoperasi')->name('det.koperasi');
    Route::get('detUser/{id}','ManagementUserController@detUser')->name('det.user');
});

app/Http/Controllers/KoperasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\KoperasiModel;
use App\JenisKoperasiModel;
use App\RekapFileModel;
use Auth;
use File;
use App\Http\Requests\KoperasiRequestStore;

class KoperasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function uniqueFilename($path, $name, $ext) {
	
        $output = $name;
        $basename = basename($name, '.' . $ext);
        $i = 2;
        
        while(File::exists($path . '/' . $output)) {
            $output = $basename . $i . '.' . $ext;
            $i ++;
        }
        
        return $output;
        
    }
    public function index()
    {
        $jenisKoperasi = JenisKoperasiModel::all();
        return view('admin.koperasi.index',['jenisKoperasi' => $jenisKoperasi]);
    }
    public function allKoperasi()
    {
        $koperasi = KoperasiModel::with(['users','jenis'])->get();        
        return view('admin.koperasi.allKoperasi',['koperasi' => $koperasi]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $client = new \GuzzleHttp\Client();
        $request = $client->get('http://api.rajaongkir.com/starter/province',
            array(
                'headers' => array(
                    'key' => '993596248bfbf46f6bae821e466878ac',
                )
            )
        );
        $response = $request->getBody()->getContents();
        $result= json_decode($response,true);

        $request2 = $client->get('http://api.rajaongkir.com/starter/city',
            array(
                'headers' => array(
                    'key' => '993596248bfbf46f6bae821e466878ac',
                )
            )
        );
        $response2 = $request2->getBody()->getContents();
        $result2= json_decode($response2,true);

        $data['provinsi'] = $result['rajaongkir']['results'];
        $data['kota'] = $result2['rajaongkir']['results'];

        $data['jenisKoperasi'] = JenisKoperasiModel::all();
        return view('admin.koperasi.create')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(KoperasiRequestStore $request)
    {
        try {            
            $koperasi = new KoperasiModel;
            $koperasi->jenis_id = $request->input('jenis_id');
            $koperasi->users_id = Auth::user()->id;
            $koperasi->nomor_spk = $request->input('nomor_spk');
            $koperasi->tgl_spk = $request->input('tgl_spk');
            $koperasi->nama_institusi = $request->input('nama_institusi');
            $koperasi->nama_ketua = $request->input('nama_ketua');
            $koperasi->alamat = $request->input('alamat');
            $koperasi->jml_anggota = $request->input('jml_anggota');
            $koperasi->provinsi = $request->input('provinsi');
            $koperasi->kab = $request->input('kab');
            $koperasi->biaya_hosting = $request->input('biaya_hosting');
            $koperasi->pic_teknik = $request->input('pic_teknik');
            $koperasi->no_telp = $request->input('no_telp');
            $koperasi->email = $request->input('email');
            $koperasi->url = $request->input('url');
            $koperasi->tgl_setup = $request->input('tgl_setup');
            $koperasi->harga_aplikasi = $request->input('harga_aplikasi');
            $koperasi->history = $request->input('history');
            $koperasi->status_pembayaran = $request->input('status_pembayaran');
            $koperasi->save();
            
            return redirect('koperasi/'.$koperasi->jenis_id)->with('success','Data Berhasil di Masukan');
        } catch (Exception $e) {
            return back()->with('danger', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $jenisKoperasi = JenisKoperasiModel::with(['koperasi','users'])->findOrFail($id);        
        return view('admin.koperasi.show',['jenisKoperasi' => $jenisKoperasi]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {        
        $client = new \GuzzleHttp\Client();
        $request = $client->get('http://api.rajaongkir.com/starter/province',
            array(
                'headers' => array(
                    'key' => '993596248bfbf46f6bae821e466878ac',
                )
            )
        );
        $response = $request->getBody()->getContents();
        $result= json_decode($response,true);

        $request2 = $client->get('http://api.rajaongkir.com/starter/city',
            array(
                'headers' => array(
                    'key' => '993596248bfbf46f6bae821e466878ac',
                )
            )
        );
        $response2 = $request2->getBody()->getContents();
        $result2= json_decode($response2,true);

        $data['koperasi'] = KoperasiModel::with(['jenis','rekap_file'])->findOrFail($id);
        $data['provinsi'] = $result['rajaongkir']['results'];
        $data['kota'] = $result2['rajaongkir']['results'];
        $data['jenis'] = JenisKoperasiModel::all();        
        return view('admin.koperasi.edit')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(KoperasiRequestStore $request, $id)
    {
        try {
            $koperasi = KoperasiModel::with('jenis')->findOrFail($id);
            $koperasi->jenis_id = $request->input('jenis_id');
            $koperasi->users_id = Auth::user()->id;
            $koperasi->nomor_spk = $request->input('nomor_spk');
            $koperasi->tgl_spk = $request->input('tgl_spk');
            $koperasi->nama_institusi = $request->input('nama_institusi');
            $koperasi->nama_ketua = $request->input('nama_ketua');
            $koperasi->alamat = $request->input('alamat');
            $koperasi->jml_anggota = $request->input('jml_anggota');
            $koperasi->provinsi = $request->input('provinsi');
            $koperasi->kab = $request->input('kab');
            $koperasi->biaya_hosting = $request->input('biaya_hosting');
            $koperasi->pic_teknik = $request->input('pic_teknik');    
            $koperasi->no_telp = $request->input('no_telp');
            $koperasi->email = $request->input('email');
            $koperasi->url = $request->input('url');
            $koperasi->tgl_setup = $request->input('tgl_setup');
            $koperasi->harga_aplikasi = $request->input('harga_aplikasi');
            $koperasi->history = $request->input('history');
            $koperasi->status_pembayaran = $request->input('status_pembayaran');

            $koperasi->save();

            return redirect('koperasi/'.$koperasi->jenis->id)->with('success', 'Data Berhasil di Perbaharui');         
        } catch (Exception $e) {
            return back()->with('danger', $e->getMessage());
        }
    }


    public function destroy(Request $request)
    {
        try {
            $id = $request->input('konfirmasiDelete');
            $koperasi = KoperasiModel::with('rekap_file')->findOrFail($id);
            foreach($koperasi->rekap_file as $value)
            {
                $path = public_path()."/files/".$value->nama;
                File::delete($path);
            }            
            $koperasi->delete();

            return back()->with('success','Data Berhasil di Hapus');
        } catch (Exception $e) {
            return back()->with('danger', $e->getMessage());
        }
    }

    public function detKoperasi($id){
        $data['dataKoperasi'] = KoperasiModel::findOrFail($id);
        return view('admin.koperasi.detKoperasi')->with($data);
    }
}

resources/views/admin/koperasi/allKoperasi.blade.php
@extends('layouts.app')
@section('title')
  Daftar Semua Koperasi
@endsection
@section('isi')
<div class="m-portlet m-portlet--head-lg">
  <div class="m-portlet__head">
    <div class="m-portlet__head-caption">
      <div class="m-portlet__head-title">
        <span class="m-portlet__head-icon">
          <i class="la la-list"></i>
        </span>
        <h3 class="m-portlet__head-text">
          Daftar Semua Koperasi
        </h3>
      </div>
    </div>
  </div>
  <div class="m-portlet__body no-pedding">
    @if(session()->has('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
            {{ session()->get('success') }}
    </div>
    @endif
    @if(session()->has('danger'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
            {{ session()->get('danger') }}
    </div>
    @endif
    <div class="list-section">
      
      <div class="m-portlet__body">
      <div class="kt-section__content">
        <table class="table">
            <thead>
              <tr>
                  <th>#</th>
                  <th>Nama Koperasi</th>
                  <th>Jenis Koperasi</th>
                  <th>Provinsi</th>
                  <th>Kab/Kota</th>
                  <th>Jumlah Anggota</th>
                  <th>Tanggal Buat</th>
                  <th>Aksi</th>
              </tr>
            </thead>
            <tbody>
              @php
                $i = 1;
              @endphp
              @forelse ($koperasi as $item) 
              <tr>
                <th scope="row">{{$i++}}</th>
                <td>{{ $item->nama_institusi}}</td>
                <td>{{ $item->jenis->nama}}</td>
                <td>{{ $item->provinsi}}</td>
                <td>{{ $item->kab}}</td>
                <td>{{ $item->jml_anggota}}</td>
                <td>{{ $item->tgl_setup}}</td>
                <td><a href="{{ url('detKoperasi/'.$item->id) }} " class="btn m-btn btn-primary btn-sm m-btn--icon m-btn--pill m-btn--air icon-only">
                    <span>
                      <i class="la la-eye"></i>
                      <span>Profil Koperasi</span>
                    </span>
                  </a></td>
                
              </tr>
              @empty
              @endforelse
            </tbody>
        </table>
      </div>
      </div>      
    </div>
  </div>
</div>
@endsection

resources/views/admin/koperasi/create.blade.php
@extends('layouts.app')
@section('title')
    Tambah Koperasi
@endsection
@section('headerPage')
    Tambah Koperasi
@endsection
@section('isi')
@if ($errors->any())    
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('success') }}
</div>
@endif
@if(session()->has('danger'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('danger') }}
</div>
@endif
<form method="POST" action="{{route('koperasi.store')}}" enctype="multipart/form-data">
    {{ csrf_field() }}
        <div class="form-group">
            <label>Jenis Koperasi</label>
            <select name="jenis_id" class="form-control" required>                
                @foreach ($jenisKoperasi as $item)
                <option value="{{$item->id}}">{{$item->nama}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label>Nomor SPK</label>
            <input type="name" class="form-control" name="nomor_spk" placeholder="Masukan Nomor SPK" required>
        </div>
        <div class="form-group">
            <label class="form-control-label">Tanggal SPK</label>                
            <div class="input-group m-input-group">
                <input type="text" name="tgl_spk" class="form-control" id="m_datepicker_1" readonly="" placeholder="Select date &amp; time" required>
                <div class="input-group-prepend"><span class="input-group-text"><i class="la la-calendar-check-o"></i></span></div>
            </div>
        </div>
        <div class="form-group">
            <label>Nama Institusi</label>
            <input type="name" class="form-control" name="nama_institusi" placeholder="Masukan Nama Institusi" required>
        </div>
        <div class="form-group">
            <label>Nama Ketua</label>
            <input type="name" class="form-control" name="nama_ketua" placeholder="Masukan Nama Ketua" required>
        </div>        
        <div class="form-group">
            <label for="">Alamat</label>
            <textarea name="alamat" cols="30" rows="10" class="form-control" placeholder="Masukan Alamat"></textarea>
        </div>
        <div class="form-group">
            <label>Jumlah Anggota</label>
            <input type="number" class="form-control" name="jml_anggota" placeholder="Masukan Jumlah Anggota">
        </div>
        <div class="form-group">
            <label>Provinsi</label>
            <select class="form-control" name="provinsi">
                @for($prov=0;$prov < count($provinsi); $prov++)
                    <option value="{{$provinsi[$prov]['province']}}">{{$provinsi[$prov]['province']}}</option>
                @endfor
            </select>
        </div>
        <div class="form-group">
        <label>Kab</label>
            <select class="form-control" name="kab">
            @for($kab=0;$kab < count($kota); $kab++)
                    <option value="{{$kota[$kab]['city_name']}}">{{$kota[$kab]['city_name']}}</option>
                @endfor
            </select>
        </div>
        <div class="form-group">
            <label>Biaya Hosting</label>
            <input type="number" class="form-control" name="biaya_hosting" placeholder="Masukan Biaya Hosting">
        </div>
        <div class="form-group">
            <label>Pic Teknik</label>
            <input type="text" class="form-control" name="pic_teknik" placeholder="Masukan Pic Teknik">
        </div>
        <div class="form-group">
            <label>Nomor Telepon</label>
            <input type="number" class="form-control" name="no_telp" placeholder="Masukan Nomor Telepon" min="11">
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" name="email" placeholder="Masukan Email">
        </div>
        <div class="form-group">
            <label>URL</label>
            <input type="url" class="form-control" name="url" placeholder="Masukan URL">
        </div>
        <div class="form-group">
            <label class="form-control-label">Tanggal Setup</label>
            <div class="input-group m-input-group">
                <input type="text" name="tgl_setup" class="form-control" id="m_datepicker_1" readonly="" placeholder="Select date &amp; time">
                <div class="input-group-prepend"><span class="input-group-text"><i class="la la-calendar-check-o"></i></span></div>
            </div>
        </div>
        <div class="form-group">
            <label>Harga Aplikasi</label>
            <input type="number" class="form-control" name="harga_aplikasi" placeholder="Masukan Harga Aplikasi">
        </div>
        <div class="form-group">
            <label>History</label>
            <input type="text" class="form-control" name="history" placeholder="Masukan History">
        </div>
        <div class="form-group">
            <label>Status Pembayaran</label>
            <select class="form-control" name="status_pembayaran">
                <option value="LUNAS">Lunas</option>
                <option value="BELUM LUNAS">Belum Lunas</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
</form>        

@endsection

resources/views/admin/koperasi/detKoperasi.blade.php
@extends('layouts.app')
@section('title')
  {{$dataKoperasi->nama_institusi}}
@endsection
@section('isi')
<div class="m-portlet m-portlet--head-lg">
  <div class="m-portlet__head">
    <div class="m-portlet__head-caption">
      <div class="m-portlet__head-title">
        <span class="m-portlet__head-icon">
          <i class="la la-list"></i>
        </span>
        <h3 class="m-portlet__head-text">
        {{$dataKoperasi->nama_institusi}}
        </h3>
      </div>
    </div>
  </div>
  <div class="m-portlet__body no-pedding">
    @if(session()->has('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
            {{ session()->get('success') }}
    </div>
    @endif
    @if(session()->has('danger'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
            {{ session()->get('danger') }}
    </div>
    @endif
    
  </div>
</div>
@endsection

resources/views/admin/koperasi/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit Koperasi
@endsection
@section('headerPage')
    Edit Koperasi
@endsection
@section('isi')
@if ($errors->any())    
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('success') }}
</div>
@endif
@if(session()->has('danger'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('danger') }}
</div>
@endif
<form method="POST" action="{{route('koperasi.update',$koperasi->id)}}" enctype="multipart/form-data">
    {{ csrf_field() }}
    {{ method_field('put') }}
        <div class="form-group">
            <label>Jenis Koperasi</label>
            <select name="jenis_id" class="form-control">                
                @foreach ($jenis as $item)
                <option value="{{$item->id}}" {{ $item->id == $koperasi->jenis->id ? "selected" : "" }}>{{$item->nama}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label>Nomor SPK</label>
            <input type="name" class="form-control" name="nomor_spk" placeholder="Masukan Nomor SPK" value="{{ $koperasi->nomor_spk }}">
        </div>
        <div class="form-group">
            <label class="form-control-label">Tanggal SPK</label>                
            <div class="input-group m-input-group">
                <input type="text" name="tgl_spk" class="form-control" id="m_datepicker_1" readonly="" placeholder="Select date &amp; time" value="{{ $koperasi->tgl_spk }}">
                <div class="input-group-prepend"><span class="input-group-text"><i class="la la-calendar-check-o"></i></span></div>
            </div>
        </div>
        <div class="form-group">
            <label>Nama Institusi</label>
            <input type="name" class="form-control" name="nama_institusi" placeholder="Masukan Nama Institusi" value="{{ $koperasi->nama_institusi }}">
        </div>
        <div class="form-group">
            <label>Nama Ketua</label>
            <input type="name" class="form-control" name="nama_ketua" placeholder="Masukan Nama Ketua" value="{{ $koperasi->nama_ketua }}">
        </div>        
        <div class="form-group">
            <label for="">Alamat</label>
            <textarea name="alamat" cols="30" rows="10" class="form-control" placeholder="Masukan Alamat">{{ $koperasi->alamat }}</textarea>
        </div>
        <div class="form-group">
            <label>Jumlah Anggota</label>
            <input type="number" class="form-control" name="jml_anggota" placeholder="Masukan Jumlah Anggota" value="{{ $koperasi->jml_anggota }}">
        </div>
        <div class="form-group">
            <label>Provinsi</label>
            <select class="form-control" name="provinsi">
                @for($prov=0;$prov < count($provinsi); $prov++)
                    <option value="{{$provinsi[$prov]['province']}}" {{ $koperasi->provinsi == $provinsi[$prov]['province'] ? 'selected' : ''}}>{{$provinsi[$prov]['province']}}</option>
                @endfor
            </select>
        </div>
        <div class="form-group">
        <label>Kab</label>
            <select class="form-control" name="kab">
            @for($kab=0;$kab < count($kota); $kab++)
                    <option value="{{$kota[$kab]['city_name']}}" {{ $koperasi->kab == $kota[$kab]['city_name'] ? 'selected' : ''}}>{{$kota[$kab]['city_name']}}</option>
                @endfor
            </select>
        </div>
        <div class="form-group">
            <label>Biaya Hosting</label>
            <input type="number" class="form-control" name="biaya_hosting" placeholder="Masukan Biaya Hosting" value="{{ $koperasi->biaya_hosting }}">
        </div>
        <div class="form-group">
            <label>Pic Teknik</label>
            <input type="text" class="form-control" name="pic_teknik" placeholder="Masukan Pic Teknik" value="{{ $koperasi->pic_teknik }}">
        </div>
        <div class="form-group">
            <label>Nomor Telepon</label>
            <input type="name" class="form-control" name="no_telp" placeholder="Masukan Nomor Telepon" value="{{ $koperasi->no_telp }}">
        </div>
        <div class="form-group">
            <label>Email</label>
            <input type="email" class="form-control" name="email" placeholder="Masukan Email" value="{{ $koperasi->email }}">
        </div>
        <div class="form-group">
            <label>URL</label>
            <input type="url" class="form-control" name="url" placeholder="Masukan URL" value="{{ $koperasi->url }}">
        </div>
        <div class="form-group">
            <label class="form-control-label">Tanggal Setup</label>
            <div class="input-group m-input-group">
                <input type="text" name="tgl_setup" class="form-control" id="m_datepicker_1" readonly="" placeholder="Select date &amp; time" value="{{ $koperasi->tgl_setup }}">
                <div class="input-group-prepend"><span class="input-group-text"><i class="la la-calendar-check-o"></i></span></div>
            </div>
        </div>
        <div class="form-group">
            <label>Harga Aplikasi</label>
            <input type="number" class="form-control" name="harga_aplikasi" placeholder="Masukan Harga Aplikasi" value="{{ $koperasi->harga_aplikasi }}">
        </div>
        <div class="form-group">
            <label>History</label>
            <input type="text" class="form-control" name="history" placeholder="Masukan History" value="{{ $koperasi->history }}">
        </div>
        <div class="form-group">
            <label>Status Pembayaran</label>
            <select class="form-control" name="status_pembayaran">
                <option value="LUNAS" {{$koperasi->status_pembayaran =="LUNAS" ? 'selected' : ''}}>Lunas</option>
                <option value="BELUM LUNAS" {{$koperasi->status_pembayaran =="BELUM LUNAS" ? 'selected' : ''}}>Belum Lunas</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
    </form>        

@endsection